### PR TITLE
Update our team

### PR DESCRIPTION
**Pull request by iLienstAr**
New role desciription + open position

Not sure if I did it correct in order to delete the picture where Manon's picture was before.
Goal is to have a grey avatar there so people see we're having an open position in case they find our vacancy :)

### CODE REVIEW

**Comment by jbelien** [comment]
@iLienstAr There was indeed some issue in your update (see 8b2c1da)

We also need a placeholder image to put for the open position (in place of the picture).

**Comment by iLienstAr** [comment]
Hey @jbelien all those little signs 🆘 
I've added a picture for the 'you' open position. Hope I did that correct 🙈

**Comment by jbelien** [comment]
Haha, if it's red ❌ there is an issue.
I've fixed it (see 5c16158777d8f35ddad1a39268d267adee3cbd34)

**Comment by jbelien** [comment]
All green ✔
Merged and deployed! 🎉

**Comment by iLienstAr** [comment]
Oh, I see that both Evan and my Twitter profile are gone now 🙈

**Comment by jbelien** [comment]
> Oh, I see that both Evan and my Twitter profile are gone now 🙈

Both your Twitter link were already empty (see a7576b8 + e9d0223).
Since they were empty, I removed it.

Make a new PR to update your Twitter link.

**Pull request merged**
